package parsers

import (
    "testing"
    "reflect"
    "github.com/geefuoco/trainer_editor/data_objects"
    "github.com/geefuoco/trainer_editor/logging"
)

func TestParsePokemonSpeciesInfo(t *testing.T) {
    t.Parallel()
    logging.EnableLogging()
    input := "testdata/pokemon_species_info_testcase.txt"

    expected := []*data_objects.PokemonSpeciesInfo{
        {
            Species:    "SPECIES_MINIOR",
            BaseHp:     60,
            BaseAtk:    60,
            BaseDef:    100,
            BaseSpd:    60,
            BaseSpAtk:  60,
            BaseSpDef:  100,
            Types:      [2]string{"TYPE_ROCK",  "TYPE_FLYING"},
        },
        {
            Species:    "SPECIES_MINIOR_CORE",
            BaseHp:     60,
            BaseAtk:    100,
            BaseDef:    60,
            BaseSpd:    120,
            BaseSpAtk:  100,
            BaseSpDef:  60,
            Types:      [2]string{"TYPE_ROCK",  "TYPE_FLYING"},
        },
        {
            Species:    "SPECIES_PIKACHU",
            BaseHp:     35,
            BaseAtk:    55,
            BaseSpd:    90,
            BaseSpAtk:  50,
            BaseDef:    40,
            BaseSpDef:  50,
            Types:      [2]string{"TYPE_ELECTRIC",  "TYPE_ELECTRIC"},
        },
        {
            Species:   "SPECIES_CASTFORM",
            BaseHp:    70,
            BaseAtk:   70,
            BaseSpd:   70,
            BaseSpAtk: 70,
            BaseDef:   70,
            BaseSpDef: 70,
            Types:     [2]string{"TYPE_NORMAL",  "TYPE_NORMAL"},
        },
        {
            Species:   "SPECIES_ARCEUS",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_NORMAL",  "TYPE_NORMAL"},
        },
        {
            Species:   "SPECIES_ORICORIO",
            BaseHp:    75,
            BaseAtk:   70,
            BaseDef:   70,
            BaseSpd:   93,
            BaseSpAtk: 98,
            BaseSpDef: 70,
            Types:     [2]string{"TYPE_FIRE",  "TYPE_FLYING"},
        },
        {
            Species:   "SPECIES_SILVALLY",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_NORMAL",  "TYPE_NORMAL"},
        },
        {
            Species:    "SPECIES_SAWSBUCK",
            BaseHp:     80,
            BaseAtk:    100,
            BaseSpd:    95,
            BaseSpAtk:  60,
            BaseDef:    70,
            BaseSpDef:  70,
            Types:      [2]string{"TYPE_NORMAL",  "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_SAWSBUCK_SUMMER",
            BaseHp:     80,
            BaseAtk:    100,
            BaseSpd:    95,
            BaseSpAtk:  60,
            BaseDef:    70,
            BaseSpDef:  70,
            Types:      [2]string{"TYPE_NORMAL",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_SAWSBUCK_AUTUMN",
            BaseHp:     80,
            BaseAtk:    100,
            BaseSpd:    95,
            BaseSpAtk:  60,
            BaseDef:    70,
            BaseSpDef:  70,
            Types:      [2]string{"TYPE_NORMAL",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_SAWSBUCK_WINTER",
            BaseHp:     80,
            BaseAtk:    100,
            BaseSpd:    95,
            BaseSpAtk:  60,
            BaseDef:    70,
            BaseSpDef:  70,
            Types:      [2]string{"TYPE_NORMAL",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_PUMPKABOO",
            BaseHp:     49,
            BaseAtk:    66,
            BaseDef:    70,
            BaseSpd:    51,
            BaseSpAtk:  44,
            BaseSpDef:  55,
            Types:      [2]string{"TYPE_GHOST",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_GOURGEIST",
            BaseHp:     65,
            BaseAtk:    90,
            BaseDef:    122,
            BaseSpd:    84,
            BaseSpAtk:  58,
            BaseSpDef:  75,
            Types:      [2]string{"TYPE_GHOST",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_PUMPKABOO_SMALL",
            BaseHp:     44,
            BaseAtk:    66,
            BaseDef:    70,
            BaseSpd:    56,
            BaseSpAtk:  44,
            BaseSpDef:  55,
            Types:      [2]string{"TYPE_GHOST",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_PUMPKABOO_SUPER",
            BaseHp:     59,
            BaseAtk:    66,
            BaseDef:    70,
            BaseSpd:    41,
            BaseSpAtk:  44,
            BaseSpDef:  55,
            Types:      [2]string{"TYPE_GHOST",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_GOURGEIST_SMALL",
            BaseHp:     55,
            BaseAtk:    85,
            BaseDef:    122,
            BaseSpd:    99,
            BaseSpAtk:  58,
            BaseSpDef:  75,
            Types:      [2]string{"TYPE_GHOST",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_GOURGEIST_LARGE",
            BaseHp:     75,
            BaseAtk:    95,
            BaseDef:    122,
            BaseSpd:    69,
            BaseSpAtk:  58,
            BaseSpDef:  75,
            Types:      [2]string{"TYPE_GHOST",    "TYPE_GRASS"},
        },
        {
            Species:    "SPECIES_CASTFORM_SUNNY",
            BaseHp:     70,
            BaseAtk:    70,
            BaseDef:    70,
            BaseSpd:    70,
            BaseSpAtk:  70,
            BaseSpDef:  70,
            Types:      [2]string{"TYPE_FIRE",    "TYPE_FIRE"},
        },
        {
            Species:    "SPECIES_CASTFORM_RAINY",
            BaseHp:     70,
            BaseAtk:    70,
            BaseDef:    70,
            BaseSpd:    70,
            BaseSpAtk:  70,
            BaseSpDef:  70,
            Types:      [2]string{"TYPE_WATER",    "TYPE_WATER"},
        },
        {
            Species:    "SPECIES_CASTFORM_SNOWY",
            BaseHp:     70,
            BaseAtk:    70,
            BaseDef:    70,
            BaseSpd:    70,
            BaseSpAtk:  70,
            BaseSpDef:  70,
            Types:      [2]string{"TYPE_ICE",    "TYPE_ICE"},
        },
        {
            Species:   "SPECIES_ORICORIO_POM_POM",
            BaseHp:    75,
            BaseAtk:   70,
            BaseDef:   70,
            BaseSpd:   93,
            BaseSpAtk: 98,
            BaseSpDef: 70,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_FLYING"},
        },
        {
            Species:   "SPECIES_ORICORIO_PAU",
            BaseHp:    75,
            BaseAtk:   70,
            BaseDef:   70,
            BaseSpd:   93,
            BaseSpAtk: 98,
            BaseSpDef: 70,
            Types:     [2]string{"TYPE_PSYCHIC",  "TYPE_FLYING"},
        },
        {
            Species:   "SPECIES_ORICORIO_SENSU",
            BaseHp:    75,
            BaseAtk:   70,
            BaseDef:   70,
            BaseSpd:   93,
            BaseSpAtk: 98,
            BaseSpDef: 70,
            Types:     [2]string{"TYPE_GHOST",  "TYPE_FLYING"},
        },
        {
            Species:   "SPECIES_ARCEUS_FIGHTING",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_FIGHTING",  "TYPE_FIGHTING"},
        },
        {
            Species:   "SPECIES_ARCEUS_FLYING",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_FLYING",  "TYPE_FLYING"},
        },
        {
            Species:   "SPECIES_ARCEUS_POISON",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_POISON",  "TYPE_POISON"},
        },
        {
            Species:   "SPECIES_ARCEUS_GROUND",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_GROUND",  "TYPE_GROUND"},
        },
        {
            Species:   "SPECIES_ARCEUS_ROCK",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_ROCK",  "TYPE_ROCK"},
        },
        {
            Species:   "SPECIES_ARCEUS_BUG",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_BUG",  "TYPE_BUG"},
        },
        {
            Species:   "SPECIES_ARCEUS_GHOST",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_GHOST",  "TYPE_GHOST"},
        },
        {
            Species:   "SPECIES_ARCEUS_STEEL",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_STEEL",  "TYPE_STEEL"},
        },
        {
            Species:   "SPECIES_ARCEUS_FIRE",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_FIRE",  "TYPE_FIRE"},
        },
        {
            Species:   "SPECIES_ARCEUS_WATER",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_WATER",  "TYPE_WATER"},
        },
        {
            Species:   "SPECIES_ARCEUS_GRASS",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_GRASS",  "TYPE_GRASS"},
        },
        {
            Species:   "SPECIES_ARCEUS_ELECTRIC",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_ELECTRIC"},
        },
        {
            Species:   "SPECIES_ARCEUS_PSYCHIC",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_PSYCHIC",  "TYPE_PSYCHIC"},
        },
        {
            Species:   "SPECIES_ARCEUS_ICE",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_ICE",  "TYPE_ICE"},
        },
        {
            Species:   "SPECIES_ARCEUS_DRAGON",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_DRAGON",  "TYPE_DRAGON"},
        },
        {
            Species:   "SPECIES_ARCEUS_DARK",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_DARK",  "TYPE_DARK"},
        },
        {
            Species:   "SPECIES_ARCEUS_FAIRY",
            BaseHp:    120,
            BaseAtk:   120,
            BaseSpd:   120,
            BaseSpAtk: 120,
            BaseDef:   120,
            BaseSpDef: 120,
            Types:     [2]string{"TYPE_FAIRY",  "TYPE_FAIRY"},
        },
        {
            Species:   "SPECIES_ROTOM",
            BaseHp:    50,
            BaseAtk:   50,
            BaseDef:   77,
            BaseSpd:   91,
            BaseSpAtk: 95,
            BaseSpDef: 77,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_GHOST"},
        },
        {
            Species:   "SPECIES_ROTOM_HEAT",
            BaseHp:    50,
            BaseAtk:   65,
            BaseDef:   107,
            BaseSpd:   86,
            BaseSpAtk: 105,
            BaseSpDef: 107,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_FIRE"},
        },
        {
            Species:   "SPECIES_ROTOM_WASH",
            BaseHp:    50,
            BaseAtk:   65,
            BaseDef:   107,
            BaseSpd:   86,
            BaseSpAtk: 105,
            BaseSpDef: 107,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_WATER"},
        },
        {
            Species:   "SPECIES_ROTOM_FROST",
            BaseHp:    50,
            BaseAtk:   65,
            BaseDef:   107,
            BaseSpd:   86,
            BaseSpAtk: 105,
            BaseSpDef: 107,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_ICE"},
        },
        {
            Species:   "SPECIES_ROTOM_FAN",
            BaseHp:    50,
            BaseAtk:   65,
            BaseDef:   107,
            BaseSpd:   86,
            BaseSpAtk: 105,
            BaseSpDef: 107,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_FLYING"},
        },
        {
            Species:   "SPECIES_ROTOM_MOW",
            BaseHp:    50,
            BaseAtk:   65,
            BaseDef:   107,
            BaseSpd:   86,
            BaseSpAtk: 105,
            BaseSpDef: 107,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_GRASS"},
        },
        {
            Species:   "SPECIES_SILVALLY_FIGHTING",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_FIGHTING",  "TYPE_FIGHTING"},
        },
        {
            Species:   "SPECIES_SILVALLY_FLYING",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_FLYING",  "TYPE_FLYING"},
        },
        {
            Species:   "SPECIES_SILVALLY_POISON",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_POISON",  "TYPE_POISON"},
        },
        {
            Species:   "SPECIES_SILVALLY_GROUND",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_GROUND",  "TYPE_GROUND"},
        },
        {
            Species:   "SPECIES_SILVALLY_ROCK",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_ROCK",  "TYPE_ROCK"},
        },
        {
            Species:   "SPECIES_SILVALLY_BUG",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_BUG",  "TYPE_BUG"},
        },
        {
            Species:   "SPECIES_SILVALLY_GHOST",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_GHOST",  "TYPE_GHOST"},
        },
        {
            Species:   "SPECIES_SILVALLY_STEEL",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_STEEL",  "TYPE_STEEL"},
        },
        {
            Species:   "SPECIES_SILVALLY_FIRE",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_FIRE",  "TYPE_FIRE"},
        },
        {
            Species:   "SPECIES_SILVALLY_WATER",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_WATER",  "TYPE_WATER"},
        },
        {
            Species:   "SPECIES_SILVALLY_GRASS",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_GRASS",  "TYPE_GRASS"},
        },
        {
            Species:   "SPECIES_SILVALLY_ELECTRIC",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_ELECTRIC",  "TYPE_ELECTRIC"},
        },
        {
            Species:   "SPECIES_SILVALLY_PSYCHIC",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_PSYCHIC",  "TYPE_PSYCHIC"},
        },
        {
            Species:   "SPECIES_SILVALLY_ICE",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_ICE",  "TYPE_ICE"},
        },
        {
            Species:   "SPECIES_SILVALLY_DRAGON",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_DRAGON",  "TYPE_DRAGON"},
        },
        {
            Species:   "SPECIES_SILVALLY_DARK",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_DARK",  "TYPE_DARK"},
        },
        {
            Species:   "SPECIES_SILVALLY_FAIRY",
            BaseHp:    95,
            BaseAtk:   95,
            BaseSpd:   95,
            BaseSpAtk: 95,
            BaseDef:   95,
            BaseSpDef: 95,
            Types:     [2]string{"TYPE_FAIRY",  "TYPE_FAIRY"},
        },
        {
            Species:   "SPECIES_AVALUGG_HISUIAN",
            BaseHp:    95,
            BaseAtk:   127,
            BaseDef:   184,
            BaseSpd:   38,
            BaseSpAtk: 34,
            BaseSpDef: 36,
            Types:     [2]string{"TYPE_ICE",  "TYPE_ROCK"},
        },
    }

    actual := ParsePokemonSpeciesInfo(input)

    missingSpeciesInfo := []string{}
    for i:=0; i < len(expected); i++ {
        expectedMon := expected[i]
        currentMon := getMon(actual, expectedMon.Species)
        if currentMon == nil {
            missingSpeciesInfo = append(missingSpeciesInfo, expectedMon.Species)
        } else {
            if !reflect.DeepEqual(currentMon, expectedMon) {
                t.Errorf("%s was not equal", currentMon.Species)
            }
        }
    }
    if len(actual) != len(expected) {
        t.Errorf("Length mismatch %d vs expected %d", len(actual), len(expected))
        t.Log("Missing: ")
        for _, sp := range missingSpeciesInfo {
            t.Log(sp)
        }
        return
    }

}

func containsMon(slice []*data_objects.PokemonSpeciesInfo, species string) bool {
    for _, x:= range slice {
        if x.Species == species {
            return true
        }
    }
    return false
}

func getMon(slice []*data_objects.PokemonSpeciesInfo, species string) *data_objects.PokemonSpeciesInfo{
    for _, x:= range slice {
        if x.Species == species {
            return x
        }
    }
    return nil
}
